-- AlterTable
ALTER TABLE "Item" ALTER COLUMN "valorEstimado" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Lance" ALTER COLUMN "valorCentavos" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Proposta" ALTER COLUMN "valorCentavos" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Sancao" ALTER COLUMN "valorMulta" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "catalogo_itens" ALTER COLUMN "valorReferencia" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "contrato_itens" ALTER COLUMN "valorUnitario" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "valorTotal" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "contratos" ALTER COLUMN "valorTotal" SET DATA TYPE DOUBLE PRECISION;
