/*
  Warnings:

  - The values [APELACAO] on the enum `TipoRecurso` will be removed. If these variants are still used in the database, this will fail.

*/
-- AlterEnum
-- This migration adds more than one value to an enum.
-- With PostgreSQL versions 11 and earlier, this is not possible
-- in a single migration. This can be worked around by creating
-- multiple migrations, each migration adding only one value to
-- the enum.


ALTER TYPE "TipoDocumento" ADD VALUE 'ADITIVO';
ALTER TYPE "TipoDocumento" ADD VALUE 'TERMO_ADITIVO';
ALTER TYPE "TipoDocumento" ADD VALUE 'TERMO_HOMOLOGACAO';
ALTER TYPE "TipoDocumento" ADD VALUE 'TERMO_JULGAMENTO';
ALTER TYPE "TipoDocumento" ADD VALUE 'TERMO_RESCISAO';
ALTER TYPE "TipoDocumento" ADD VALUE 'TERMO_ACEITACAO';
ALTER TYPE "TipoDocumento" ADD VALUE 'TERMO_ENCERRAMENTO';
ALTER TYPE "TipoDocumento" ADD VALUE 'PROPOSTA_TECNICA';
ALTER TYPE "TipoDocumento" ADD VALUE 'PROPOSTA_COMERCIAL';
ALTER TYPE "TipoDocumento" ADD VALUE 'PROPOSTA_FINANCEIRA';
ALTER TYPE "TipoDocumento" ADD VALUE 'PLANILHA_PRECOS';
ALTER TYPE "TipoDocumento" ADD VALUE 'MEMORIAL_DESCRITIVO';
ALTER TYPE "TipoDocumento" ADD VALUE 'CRONOGRAMA_EXECUCAO';
ALTER TYPE "TipoDocumento" ADD VALUE 'HABILITACAO_JURIDICA';
ALTER TYPE "TipoDocumento" ADD VALUE 'HABILITACAO_TECNICA';
ALTER TYPE "TipoDocumento" ADD VALUE 'HABILITACAO_FISCAL';
ALTER TYPE "TipoDocumento" ADD VALUE 'HABILITACAO_ECONOMICA';
ALTER TYPE "TipoDocumento" ADD VALUE 'HABILITACAO_QUALIFICACAO';
ALTER TYPE "TipoDocumento" ADD VALUE 'CERTIDAO_NEGATIVA_DEBITOS';
ALTER TYPE "TipoDocumento" ADD VALUE 'CERTIDAO_POSITIVA_COM_EFEITO_NEGATIVA';
ALTER TYPE "TipoDocumento" ADD VALUE 'CERTIDAO_TRABALHISTA';
ALTER TYPE "TipoDocumento" ADD VALUE 'CERTIDAO_FGTS';
ALTER TYPE "TipoDocumento" ADD VALUE 'CERTIDAO_INSS';
ALTER TYPE "TipoDocumento" ADD VALUE 'CERTIDAO_FALENCIA';
ALTER TYPE "TipoDocumento" ADD VALUE 'CERTIDAO_CRIMINAL';
ALTER TYPE "TipoDocumento" ADD VALUE 'CERTIDAO_ELEITORAL';
ALTER TYPE "TipoDocumento" ADD VALUE 'CERTIDAO_MILITAR';
ALTER TYPE "TipoDocumento" ADD VALUE 'CERTIDAO_ESTADUAL';
ALTER TYPE "TipoDocumento" ADD VALUE 'CERTIDAO_MUNICIPAL';
ALTER TYPE "TipoDocumento" ADD VALUE 'CERTIDAO_FEDERAL';
ALTER TYPE "TipoDocumento" ADD VALUE 'DECLARACAO_DE_NAO_INCUMBENCIA';
ALTER TYPE "TipoDocumento" ADD VALUE 'DECLARACAO_DE_VERACIDADE';
ALTER TYPE "TipoDocumento" ADD VALUE 'DECLARACAO_DE_COMPATIBILIDADE';
ALTER TYPE "TipoDocumento" ADD VALUE 'DECLARACAO_DE_ATENDIMENTO';
ALTER TYPE "TipoDocumento" ADD VALUE 'DECLARACAO_DE_CAPACIDADE';
ALTER TYPE "TipoDocumento" ADD VALUE 'DECLARACAO_DE_EXPERIENCIA';
ALTER TYPE "TipoDocumento" ADD VALUE 'DECLARACAO_DE_QUALIFICACAO';
ALTER TYPE "TipoDocumento" ADD VALUE 'DECLARACAO_DE_ME_EPP';
ALTER TYPE "TipoDocumento" ADD VALUE 'COMPROVANTE_ENDERECO';
ALTER TYPE "TipoDocumento" ADD VALUE 'COMPROVANTE_INSCRICAO';
ALTER TYPE "TipoDocumento" ADD VALUE 'COMPROVANTE_CAPITAL';
ALTER TYPE "TipoDocumento" ADD VALUE 'COMPROVANTE_EXPERIENCIA';
ALTER TYPE "TipoDocumento" ADD VALUE 'COMPROVANTE_QUALIFICACAO';
ALTER TYPE "TipoDocumento" ADD VALUE 'COMPROVANTE_PAGAMENTO';
ALTER TYPE "TipoDocumento" ADD VALUE 'COMPROVANTE_ENTREGA';
ALTER TYPE "TipoDocumento" ADD VALUE 'COMPROVANTE_ASSINATURA';
ALTER TYPE "TipoDocumento" ADD VALUE 'MANUAL_TECNICO';
ALTER TYPE "TipoDocumento" ADD VALUE 'ESPECIFICACAO_TECNICA';
ALTER TYPE "TipoDocumento" ADD VALUE 'DESENHO_TECNICO';
ALTER TYPE "TipoDocumento" ADD VALUE 'FOTO';
ALTER TYPE "TipoDocumento" ADD VALUE 'VIDEO';
ALTER TYPE "TipoDocumento" ADD VALUE 'AUDIO';

-- AlterEnum
BEGIN;
CREATE TYPE "TipoRecurso_new" AS ENUM ('IMPUGNACAO', 'RECURSO', 'RECONSIDERACAO');
ALTER TABLE "Recurso" ALTER COLUMN "tipo" TYPE "TipoRecurso_new" USING ("tipo"::text::"TipoRecurso_new");
ALTER TYPE "TipoRecurso" RENAME TO "TipoRecurso_old";
ALTER TYPE "TipoRecurso_new" RENAME TO "TipoRecurso";
DROP TYPE "TipoRecurso_old";
COMMIT;
